### ISSUE TITLE
[Bug] FilterButton.lua Error

### ISSUE THREAD

**Issue by Starlynk1** [Noshei/GatheringTracker#20]
Error I've been getting since latest updates.

```
31x GatheringTracker/FilterButton.lua:81: attempt to index field 'button' (a nil value)
[string "@GatheringTracker/FilterButton.lua"]:81: in function `?'
[string "@GatheringTracker/Utilities.lua"]:91: in function <GatheringTracker/Utilities.lua:85>

Locals:
self = <table> {
 expansionsOrder = <table> {
 }
 modules = <table> {
 }
 count = <table> {
 }
 media = <table> {
 }
 db = <table> {
 }
 NotificationPause = true
 Options = <table> {
 }
 categoriesOrder = <table> {
 }
 Notifications = <table> {
 }
 DebugCount = 0
 name = "GatheringTracker"
 IDs = <table> {
 }
 PlayerEnteringWorld = false
 tsmLoaded = true
 Pools = <table> {
 }
 baseName = "GatheringTracker"
 waitTable = <table> {
 }
 defaultModuleState = true
 groupMode = "WHISPER"
 Enabled = true
 Player = "Starlyte"
 TSM = "DBMarket"
 metaData = <table> {
 }
 defaults = <table> {
 }
 ItemData = <table> {
 }
 categories = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 GlobalStartTime = 1727313322
 sender = <table> {
 }
 orderedModules = <table> {
 }
 baseFrame = <table> {
 }
 enabledState = true
 Display = <table> {
 }
 expansions = <table> {
 }
 InventoryData = <table> {
 }
}
UITop = 1175
UILeft = 25
backdropTop = 971.666565
backdropLeft = 40.833305
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'button' (a nil value)"
GT = <table> {
 expansionsOrder = <table> {
 }
 modules = <table> {
 }
 count = <table> {
 }
 media = <table> {
 }
 db = <table> {
 }
 NotificationPause = true
 Options = <table> {
 }
 categoriesOrder = <table> {
 }
 Notifications = <table> {
 }
 DebugCount = 0
 name = "GatheringTracker"
 IDs = <table> {
 }
 PlayerEnteringWorld = false
 tsmLoaded = true
 Pools = <table> {
 }
 baseName = "GatheringTracker"
 waitTable = <table> {
 }
 defaultModuleState = true
 groupMode = "WHISPER"
 Enabled = true
 Player = "Starlyte"
 TSM = "DBMarket"
 metaData = <table> {
 }
 defaults = <table> {
 }
 ItemData = <table> {
 }
 categories = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 GlobalStartTime = 1727313322
 sender = <table> {
 }
 orderedModules = <table> {
 }
 baseFrame = <table> {
 }
 enabledState = true
 Display = <table> {
 }
 expansions = <table> {
 }
 InventoryData = <table> {
 }
}
```

**Comment by Noshei** [comment]
This is fixed in v2.5.3, which should be up on curse shortly.

**Comment by Starlynk1** [comment]
Still getting an LUA error with the filter button being disabled. 
```
3x GatheringTracker/FilterButton.lua:140: attempt to index field 'button' (a nil value)
[string "@GatheringTracker/FilterButton.lua"]:140: in function <GatheringTracker/FilterButton.lua:105>
[string "=[C]"]: in function `securecallfunction'
[string "@Blizzard_Menu/Menu.lua"]:2417: in function `PopulateDescription'
[string "@Blizzard_Menu/MenuUtil.lua"]:157: in function `CreateContextMenu'
[string "@GatheringTracker/FilterButton.lua"]:272: in function `GenerateFiltersMenu'
[string "@GatheringTracker/Broker.lua"]:28: in function `OnClick'
[string "@BugSack/Libs/LibDBIcon-1.0-55/LibDBIcon-1.0.lua"]:179: in function <BugSack/Libs/LibDBIcon-1.0/LibDBIcon-1.0.lua:177>

Locals:
frame = LibDBIcon10_Gathering Tracker {
 fadeOut = AnimationGroup {
 }
 dataObject = <table> {
 }
 isMouseDown = false
 db = <table> {
 }
 icon = Texture {
 }
}
rootDescription = <table> {
}
(for state) = <table> {
 7 = "Legion"
 1 = "Classic"
 2 = "BC"
 4 = "Cata"
 8 = "BFA"
 9 = "SL"
 5 = "MoP"
 10 = "DF"
 3 = "Wrath"
 6 = "WoD"
 12 = "Other"
 11 = "TWW"
}
(for control) = 1
expansionIndex = 1
expansion = "Classic"
(*temporary) = nil
(*temporary) = <table> {
 defaultResponse = 2
 text = "Classic"
}
(*temporary) = <table> {
 proxy = <table> {
 }
 initializers = <table> {
 }
 elementDescriptions = <table> {
 }
 gridDirection = 1
 sharedMenuProperties = <table> {
 }
 finalInitializer = <table> {
 }
 finalizeGridLayout = <table> {
 }
 elementFactory = <table> {
 }
}
(*temporary) = <table> {
 defaultResponse = 2
 text = "Classic"
}
(*temporary) = <table> {
 defaultResponse = 2
 text = "Classic"
}
(*temporary) = <table> {
 defaultResponse = 2
 text = "Classic"
}
(*temporary) = <table> {
 proxy = <table> {
 }
 initializers = <table> {
 }
 elementDescriptions = <table> {
 }
 gridDirection = 1
 sharedMenuProperties = <table> {
 }
 finalInitializer = <table> {
 }
 finalizeGridLayout = <table> {
 }
 elementFactory = <table> {
 }
}
(*temporary) = <table> {
 defaultResponse = 2
 text = "Classic"
}
(*temporary) = <table> {
 proxy = <table> {
 }
 initializers = <table> {
 }
 elementDescriptions = <table> {
 }
 gridDirection = 1
 sharedMenuProperties = <table> {
 }
 finalInitializer = <table> {
 }
 finalizeGridLayout = <table> {
 }
 elementFactory = <table> {
 }
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = <table> {
 tbl = <table> {
 }
}
(*temporary) = <table> {
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index field 'button' (a nil value)"
GT = <table> {
 expansionsOrder = <table> {
 }
 modules = <table> {
 }
 count = <table> {
 }
 media = <table> {
 }
 db = <table> {
 }
 NotificationPause = true
 Options = <table> {
 }
 categoriesOrder = <table> {
 }
 Notifications = <table> {
 }
 DebugCount = 0
 name = "GatheringTracker"
 IDs = <table> {
 }
 PlayerEnteringWorld = false
 Pools = <table> {
 }
 baseName = "GatheringTracker"
 waitTable = <table> {
 }
 defaultModuleState = true
 priceSources = <table> {
 }
 groupMode = "WHISPER"
 Enabled = true
 Player = "Starlyte"
 TSM = "DBMarket"
 metaData = <table> {
 }
 defaults = <table> {
 }
 ItemData = <table> {
 }
 categories = <table> {
 }
 defaultModuleLibraries = <table> {
 }
 GlobalStartTime = 1728403135
 sender = <table> {
 }
 orderedModules = <table> {
 }
 baseFrame = <table> {
 }
 enabledState = true
 Display = <table> {
 }
 expansions = <table> {
 }
 InventoryData = <table> {
 }
}
```

**Comment by Starlynk1** [comment]
Using version 2.5.4

**Comment by Noshei** [comment]
are you using a broker type addon, and do you have Gathering Tracker shown in that?

**Comment by Starlynk1** [comment]
Nope, just use the default UI minimap and the blizz addon container, at least I think that is a Blizz thing added with 11.0.5
![992f162a0747bfe4d5427481ce96151c](https://github.com/user-attachments/assets/5d564012-21b4-4b00-97b6-6fc80ccc3d26)

**Comment by Starlynk1** [comment]
Inside that addon container, I can say that it doesn't work the same as when using the actual minimap button. Left click does not open the filter menu, it enables/disables the tracker

**Comment by Noshei** [comment]
yeah, I added the addon container a long time ago and didn't want to change the way it functioned when I added the minimap icon.  The minimap icon actually uses the same code as the broker, so makes sense you are using the minimap icon.

I found the issue and it will be resolved in 2.5.5, which should be released shortly.

**Comment by Starlynk1** [comment]
awesome, thank you!
